-- Enrich Guinea mmd_zones — Conakry communes/quartiers, Labé quartiers, Mali prefecture, Dougountouny districts
-- Safe upsert via zone_code; does not touch taxi, delivery, dispatch, or launch_status.

begin;

insert into public.mmd_zones (
  country_code, region_name, prefecture_name, city_name, commune_name, quartier_name,
  zone_code, zone_name, is_active
) values
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Sonfonia', null, 'gn_conakry_sonfonia', 'Sonfonia', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Kaloum', 'Boulbinet', 'gn_conakry_kaloum_boulbinet', 'Boulbinet', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Kaloum', 'Almamya', 'gn_conakry_kaloum_almamya', 'Almamya', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Kaloum', 'Coronthie', 'gn_conakry_kaloum_coronthie', 'Coronthie', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Kaloum', 'Kaloum', 'gn_conakry_kaloum_kaloum', 'Kaloum', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Kaloum', 'Kouléwondy', 'gn_conakry_kaloum_koulewondy', 'Kouléwondy', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Kaloum', 'Manquepas', 'gn_conakry_kaloum_manquepas', 'Manquepas', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Kaloum', 'Sandervalia', 'gn_conakry_kaloum_sandervalia', 'Sandervalia', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Kaloum', 'Sans-fil', 'gn_conakry_kaloum_sans_fil', 'Sans-fil', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Kaloum', 'Témitaye', 'gn_conakry_kaloum_temitaye', 'Témitaye', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Kaloum', 'Tombo', 'gn_conakry_kaloum_tombo', 'Tombo', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Dixinn', 'Belle-vue école', 'gn_conakry_dixinn_belle_vue_ecole', 'Belle-vue école', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Dixinn', 'Belle-vue marché', 'gn_conakry_dixinn_belle_vue_marche', 'Belle-vue marché', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Dixinn', 'Camayenne', 'gn_conakry_dixinn_camayenne', 'Camayenne', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Dixinn', 'Cameroun', 'gn_conakry_dixinn_cameroun', 'Cameroun', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Dixinn', 'Dixinn-cité 1', 'gn_conakry_dixinn_dixinn_cite_1', 'Dixinn-cité 1', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Dixinn', 'Dixinn-cité 2', 'gn_conakry_dixinn_dixinn_cite_2', 'Dixinn-cité 2', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Dixinn', 'Dixinn-gare', 'gn_conakry_dixinn_dixinn_gare', 'Dixinn-gare', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Dixinn', 'Dixinn-gare-rails', 'gn_conakry_dixinn_dixinn_gare_rails', 'Dixinn-gare-rails', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Dixinn', 'Dixinn-mosquée', 'gn_conakry_dixinn_dixinn_mosquee', 'Dixinn-mosquée', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Dixinn', 'Dixinn-port', 'gn_conakry_dixinn_dixinn_port', 'Dixinn-port', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Dixinn', 'Hafia 1', 'gn_conakry_dixinn_hafia_1', 'Hafia 1', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Dixinn', 'Hafia 2', 'gn_conakry_dixinn_hafia_2', 'Hafia 2', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Dixinn', 'Hafia-minière', 'gn_conakry_dixinn_hafia_miniere', 'Hafia-minière', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Dixinn', 'Hafia-mosquée', 'gn_conakry_dixinn_hafia_mosquee', 'Hafia-mosquée', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Dixinn', 'Kénien', 'gn_conakry_dixinn_kenien', 'Kénien', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Dixinn', 'Landréah', 'gn_conakry_dixinn_landreah', 'Landréah', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Dixinn', 'Minière-cité', 'gn_conakry_dixinn_miniere_cite', 'Minière-cité', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Bantounka I', 'gn_conakry_ratoma_bantounka_i', 'Bantounka I', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Bantounka II', 'gn_conakry_ratoma_bantounka_ii', 'Bantounka II', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Dar Es Salam I', 'gn_conakry_ratoma_dar_es_salam_i', 'Dar Es Salam I', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Dar Es Salam II', 'gn_conakry_ratoma_dar_es_salam_ii', 'Dar Es Salam II', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Hamdallaye I', 'gn_conakry_ratoma_hamdallaye_i', 'Hamdallaye I', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Hamdallaye II', 'gn_conakry_ratoma_hamdallaye_ii', 'Hamdallaye II', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Hamdallaye Mosquée', 'gn_conakry_ratoma_hamdallaye_mosquee', 'Hamdallaye Mosquée', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Kaporo Centre', 'gn_conakry_ratoma_kaporo_centre', 'Kaporo Centre', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Kaporo Rails', 'gn_conakry_ratoma_kaporo_rails', 'Kaporo Rails', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Kipé', 'gn_conakry_ratoma_kipe', 'Kipé', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Kobaya', 'gn_conakry_ratoma_kobaya', 'Kobaya', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Koloma I', 'gn_conakry_ratoma_koloma_i', 'Koloma I', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Koloma II', 'gn_conakry_ratoma_koloma_ii', 'Koloma II', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Lambanyi', 'gn_conakry_ratoma_lambanyi', 'Lambanyi', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Nasroullaye', 'gn_conakry_ratoma_nasroullaye', 'Nasroullaye', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Nongo', 'gn_conakry_ratoma_nongo', 'Nongo', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Nongo Tady', 'gn_conakry_ratoma_nongo_tady', 'Nongo Tady', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Ratoma Centre', 'gn_conakry_ratoma_ratoma_centre', 'Ratoma Centre', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Ratoma Dispensaire', 'gn_conakry_ratoma_ratoma_dispensaire', 'Ratoma Dispensaire', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Simbaya Gare', 'gn_conakry_ratoma_simbaya_gare', 'Simbaya Gare', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Soloprimo', 'gn_conakry_ratoma_soloprimo', 'Soloprimo', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Sonfonia Centre I', 'gn_conakry_ratoma_sonfonia_centre_i', 'Sonfonia Centre I', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Sonfonia Centre II', 'gn_conakry_ratoma_sonfonia_centre_ii', 'Sonfonia Centre II', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Sonfonia Gare I', 'gn_conakry_ratoma_sonfonia_gare_i', 'Sonfonia Gare I', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Sonfonia Gare II', 'gn_conakry_ratoma_sonfonia_gare_ii', 'Sonfonia Gare II', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Soumabossia', 'gn_conakry_ratoma_soumabossia', 'Soumabossia', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Taouyah', 'gn_conakry_ratoma_taouyah', 'Taouyah', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Wanindara I', 'gn_conakry_ratoma_wanindara_i', 'Wanindara I', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Wanindara II', 'gn_conakry_ratoma_wanindara_ii', 'Wanindara II', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Wanindara III', 'gn_conakry_ratoma_wanindara_iii', 'Wanindara III', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Wareya', 'gn_conakry_ratoma_wareya', 'Wareya', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Yattaya Centre', 'gn_conakry_ratoma_yattaya_centre', 'Yattaya Centre', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Yattaya Fossedè', 'gn_conakry_ratoma_yattaya_fossede', 'Yattaya Fossedè', true),
  ('GN', 'Conakry', 'Conakry', 'Conakry', 'Ratoma', 'Yembaya', 'gn_conakry_ratoma_yembaya', 'Yembaya', true),
  ('GN', 'Labé', 'Labé', 'Labé', 'Labé', 'Daka 1', 'gn_labe_labe_daka_1', 'Daka 1', true),
  ('GN', 'Labé', 'Labé', 'Labé', 'Labé', 'Daka 2', 'gn_labe_labe_daka_2', 'Daka 2', true),
  ('GN', 'Labé', 'Labé', 'Labé', 'Labé', 'Dongora', 'gn_labe_labe_dongora', 'Dongora', true),
  ('GN', 'Labé', 'Labé', 'Labé', 'Labé', 'Dow Saré', 'gn_labe_labe_dow_sare', 'Dow Saré', true),
  ('GN', 'Labé', 'Labé', 'Labé', 'Labé', 'Konkola', 'gn_labe_labe_konkola', 'Konkola', true),
  ('GN', 'Labé', 'Labé', 'Labé', 'Labé', 'Kouroula', 'gn_labe_labe_kouroula', 'Kouroula', true),
  ('GN', 'Labé', 'Labé', 'Labé', 'Labé', 'Mairie', 'gn_labe_labe_mairie', 'Mairie', true),
  ('GN', 'Labé', 'Labé', 'Labé', 'Labé', 'Madina', 'gn_labe_labe_madina', 'Madina', true),
  ('GN', 'Labé', 'Labé', 'Labé', 'Labé', 'Mosquée', 'gn_labe_labe_mosquee', 'Mosquée', true),
  ('GN', 'Labé', 'Labé', 'Labé', 'Labé', 'Pounthioun', 'gn_labe_labe_pounthioun', 'Pounthioun', true),
  ('GN', 'Labé', 'Labé', 'Labé', 'Labé', 'Tata 1', 'gn_labe_labe_tata_1', 'Tata 1', true),
  ('GN', 'Labé', 'Labé', 'Labé', 'Labé', 'Tata 2', 'gn_labe_labe_tata_2', 'Tata 2', true),
  ('GN', 'Labé', 'Labé', 'Labé', 'Labé', 'Bambaya', 'gn_labe_labe_bambaya', 'Bambaya', true),
  ('GN', 'Labé', 'Labé', 'Labé', 'Labé', 'Companya', 'gn_labe_labe_companya', 'Companya', true),
  ('GN', 'Labé', 'Labé', 'Labé', 'Labé', 'Dongol', 'gn_labe_labe_dongol', 'Dongol', true),
  ('GN', 'Labé', 'Labé', 'Labé', 'Labé', 'Dongol Dayébhé', 'gn_labe_labe_dongol_dayebhe', 'Dongol Dayébhé', true),
  ('GN', 'Labé', 'Labé', 'Labé', 'Labé', 'Fady', 'gn_labe_labe_fady', 'Fady', true),
  ('GN', 'Labé', 'Labé', 'Labé', 'Labé', 'Fafabhé', 'gn_labe_labe_fafabhe', 'Fafabhé', true),
  ('GN', 'Labé', 'Labé', 'Labé', 'Labé', 'Falo Bowé', 'gn_labe_labe_falo_bowe', 'Falo Bowé', true),
  ('GN', 'Labé', 'Labé', 'Labé', 'Labé', 'Horé Saala', 'gn_labe_labe_hore_saala', 'Horé Saala', true),
  ('GN', 'Labé', 'Labé', 'Labé', 'Labé', 'Koulidara', 'gn_labe_labe_koulidara', 'Koulidara', true),
  ('GN', 'Labé', 'Labé', 'Labé', 'Labé', 'Lombonna', 'gn_labe_labe_lombonna', 'Lombonna', true),
  ('GN', 'Labé', 'Labé', 'Labé', 'Labé', 'Nadhel', 'gn_labe_labe_nadhel', 'Nadhel', true),
  ('GN', 'Labé', 'Labé', 'Labé', 'Labé', 'Petewel', 'gn_labe_labe_petewel', 'Petewel', true),
  ('GN', 'Labé', 'Labé', 'Labé', 'Labé', 'Poreko', 'gn_labe_labe_poreko', 'Poreko', true),
  ('GN', 'Labé', 'Labé', 'Labé', 'Labé', 'Saala N''Douyebhe', 'gn_labe_labe_saala_ndouyebhe', 'Saala N''Douyebhe', true),
  ('GN', 'Labé', 'Labé', 'Labé', 'Labé', 'Safatou 1', 'gn_labe_labe_safatou_1', 'Safatou 1', true),
  ('GN', 'Labé', 'Labé', 'Labé', 'Labé', 'Safatou 2', 'gn_labe_labe_safatou_2', 'Safatou 2', true),
  ('GN', 'Labé', 'Labé', 'Labé', 'Labé', 'Bowloko', 'gn_labe_labe_bowloko', 'Bowloko', true),
  ('GN', 'Labé', 'Mali', 'Mali', null, null, 'gn_labe_mali_prefecture', 'Préfecture de Mali', true),
  ('GN', 'Labé', 'Mali', 'Mali', null, null, 'gn_labe_mali_centre', 'Mali Centre', true),
  ('GN', 'Labé', 'Mali', 'Dougountouny', null, null, 'gn_labe_mali_dougountouny', 'Dougountouny', true),
  ('GN', 'Labé', 'Mali', 'Balaki', null, null, 'gn_labe_mali_balaki', 'Balaki', true),
  ('GN', 'Labé', 'Mali', 'Donghol Sigon', null, null, 'gn_labe_mali_donghol_sigon', 'Donghol Sigon', true),
  ('GN', 'Labé', 'Mali', 'Fougou', null, null, 'gn_labe_mali_fougou', 'Fougou', true),
  ('GN', 'Labé', 'Mali', 'Gayah', null, null, 'gn_labe_mali_gayah', 'Gayah', true),
  ('GN', 'Labé', 'Mali', 'Hidayatou', null, null, 'gn_labe_mali_hidayatou', 'Hidayatou', true),
  ('GN', 'Labé', 'Mali', 'Lebekere', null, null, 'gn_labe_mali_lebekere', 'Lebekere', true),
  ('GN', 'Labé', 'Mali', 'Madina Wora', null, null, 'gn_labe_mali_madina_wora', 'Madina Wora', true),
  ('GN', 'Labé', 'Mali', 'Salambande', null, null, 'gn_labe_mali_salambande', 'Salambande', true),
  ('GN', 'Labé', 'Mali', 'Téliré', null, null, 'gn_labe_mali_telire', 'Téliré', true),
  ('GN', 'Labé', 'Mali', 'Touba', null, null, 'gn_labe_mali_touba', 'Touba', true),
  ('GN', 'Labé', 'Mali', 'Yembereng', null, null, 'gn_labe_mali_yembereng', 'Yembereng', true),
  ('GN', 'Labé', 'Mali', 'Dougountouny', 'Dougountouny', 'Dougountouny Centre', 'gn_labe_mali_dougountouny_dougountouny_centre', 'Dougountouny Centre', true),
  ('GN', 'Labé', 'Mali', 'Dougountouny', 'Dougountouny', 'Djendjen', 'gn_labe_mali_dougountouny_djendjen', 'Djendjen', true),
  ('GN', 'Labé', 'Mali', 'Dougountouny', 'Dougountouny', 'Djohére', 'gn_labe_mali_dougountouny_djohere', 'Djohére', true),
  ('GN', 'Labé', 'Mali', 'Dougountouny', 'Dougountouny', 'Badougoula', 'gn_labe_mali_dougountouny_badougoula', 'Badougoula', true),
  ('GN', 'Labé', 'Mali', 'Dougountouny', 'Dougountouny', 'Wanssan', 'gn_labe_mali_dougountouny_wanssan', 'Wanssan', true),
  ('GN', 'Labé', 'Mali', 'Dougountouny', 'Dougountouny', 'Bamba Saberé', 'gn_labe_mali_dougountouny_bamba_sabere', 'Bamba Saberé', true),
  ('GN', 'Labé', 'Mali', 'Dougountouny', 'Dougountouny', 'Boulleré', 'gn_labe_mali_dougountouny_boullere', 'Boulleré', true),
  ('GN', 'Labé', 'Mali', 'Dougountouny', 'Dougountouny', 'Kokouma', 'gn_labe_mali_dougountouny_kokouma', 'Kokouma', true),
  ('GN', 'Labé', 'Mali', 'Dougountouny', 'Dougountouny', 'Daara', 'gn_labe_mali_dougountouny_daara', 'Daara', true)
on conflict (zone_code) do update
set
  zone_name = excluded.zone_name,
  region_name = excluded.region_name,
  prefecture_name = excluded.prefecture_name,
  city_name = excluded.city_name,
  commune_name = excluded.commune_name,
  quartier_name = excluded.quartier_name,
  is_active = excluded.is_active,
  updated_at = now();

commit;
